# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Internship Catalog"
  default: index
  tokenTimeout: 10
  url: "vandyhacks-cvetanovskaa.c9users.io:8080/"
  

databases:
  dmz:
    filename: data/dmz.sqlite
  
organizationType:
  - option: "Profit"
  - option: "Non-profit"
    
paidType:
  - option: "Hourly"
  - option: "Compensation"
sys:
  debug: True
  host: "0.0.0.0"
  port: 8080

electionsMenu:
  - title: "Home"
    link: "/user/upcomingElections"
  - title: "Personal Issue Views"
    link: "/user/rateIssues"

    
table_entry:
  - header: "Name"
  - header: "Date"
   
flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM
  
issuesList:
  - option: "Women and Minorities"
    explanation: "Legally Require Hiring Women and Minorities"
  - option: "Same-Sex Marriage"
    explanation: ""
  - option: "Guns"
    explanation: "Gun Rights"
  - option: "Obamacare"
    explanation: "Obamacare"
  - option: "Immigration"
    explanation: "Immigration Reform"
   
signature: "Thank you for using the Internship Catalog System"
controllers: !include:controllers.yaml
