# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Internship Catalog"
  default: index
  tokenTimeout: 10
  url: "vandyhacks-cvetanovskaa.c9users.io:8080/"

keys:
  googleapi: "AIzaSyBcM1yBZ6R7Bva6xnluLFL6L_bzhHiU_Sw"
  ibmapi: "b3ab2920d3b2a7215389dddeec54bf1ed0724ae1"


databases:
  dmz:
    filename: data/dmz.sqlite

organizationType:
  - option: "Profit"
  - option: "Non-profit"

paidType:
  - option: "Hourly"
  - option: "Compensation"
sys:
  debug: True
  host: "0.0.0.0"
  port: 8080

electionsMenu:
  - title: "Home"
    link: "/user/upcomingElections"
  - title: "Personal Issue Views"
    link: "/user/rateIssues"


table_entry:
  - header: "Name"
  - header: "Date"

flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM

issuesList:
  - option: "Abortion"
    explanation: "Abortion rights"
  - option: "Women and Minorities"
    explanation: "Legally Require Hiring Women and Minorities"
  - option: "Same-Sex Marriage"
    explanation: ""
  - option: "Public Faith"
    explanation: "Faith in Schools"
  - option: "Environment"
    explanation: "Less Environmental Regulation"
  - option: "Campaign Finance"
    explanation: "Campaign Finance Reform"
  - option: "Crime"
    explanation: "Stricter Criminal Sentencing"
  - option: "Guns"
    explanation: "Gun Rights"
  - option: "Obamacare"
    explanation: ""
  - option: "Schools"
    explanation: "School Vouchers"
  - option: "Energy"
    explanation: "Prioritizing Green Energy"
  - option: "Drugs"
    explanation: "Stricter Drug Laws"
  - option: "Stimulus"
    explanation: "Stimulus Policies"
  - option: "Taxes"
    explanation: "Higher Taxes on Wealthy"
  - option: "Immigration"
    explanation: "Immigration Reform"
  - option: "Social Security"
    explanation: "Privatizing Social Security"
  - option: "Trade"
    explanation: "Free Trade"
  - option: "Military"
    explanation: "Robust Military"
  - option: "America"
    explanation: "Supporting American Exceptionalism"
  - option: "Foreign Policy"
    explanation: "Avoiding Foreign Entanglements"

signature: "Thank you for using the Internship Catalog System"
controllers: !include:controllers.yaml
